version: '3'

services:
  mysql:
    image: mysql:8
    container_name: java-mysql-weather
    environment:
      - MYSQL_ROOT_PASSWORD=1917
      - MYSQL_DATABASE=test
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    ports:
      - '3306:3306'







